### ISSUE TITLE
Error when running ./bldr deploy and selecting project 

### ISSUE THREAD

**Issue by Jenniferstrej** [elifesciences/builder#164]
Example:

```
➜  builder git:(master) ./bldr deploy
2017-07-19 11:52:46,281 - WARNING - MainProcess - buildercore.decorators - TODO: `_pick` renamed from `_pick` to something. `choose` ?
please pick: (project)
1 - api-dummy
2 - elife-bot
3 - elife-dashboard
4 - journal
5 - lax
> 1
2017-07-19 11:52:50,147 - INFO - MainProcess - deploy - stack 'api-dummy' doesn't exist, creating
Traceback (most recent call last):
  File "/Users/jen.strejevitch/Projects/de-elife/builder/venv/lib/python2.7/site-packages/fabric/main.py", line 745, in main
    *args, **kwargs
  File "/Users/jen.strejevitch/Projects/de-elife/builder/venv/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/jen.strejevitch/Projects/de-elife/builder/venv/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/jen.strejevitch/Projects/de-elife/builder/src/decorators.py", line 58, in wrap2
    return func(pname, *args, **kwargs)
  File "/Users/jen.strejevitch/Projects/de-elife/builder/src/decorators.py", line 155, in _wrapper
    res = func(*args, **kwargs)
  File "/Users/jen.strejevitch/Projects/de-elife/builder/src/decorators.py", line 20, in wrap
    result = fn(*args, **kw)
  File "/Users/jen.strejevitch/Projects/de-elife/builder/src/deploy.py", line 42, in deploy
    more_context = cfngen.choose_config(stackname)
  File "/Users/jen.strejevitch/Projects/de-elife/builder/src/buildercore/cfngen.py", line 221, in choose_config
    (pname, instance_id) = core.parse_stackname(stackname)
  File "/Users/jen.strejevitch/Projects/de-elife/builder/src/buildercore/core.py", line 344, in parse_stackname
    raise ValueError("could not parse given stackname %r" % stackname)
ValueError: could not parse given stackname 'api-dummy'
```

However when I ran 

```./bldr deploy:api-dummy,prod```

 it starts creating the stack correctly.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder/commit/0615c326e3feb7466b7433172a40e6c3ae14edcc should solve this
