### ISSUE TITLE
Can't deploying a master server for the first time

### ISSUE THREAD

**Issue by pyotr** [elifesciences/builder#384]
Hello!

i tried to run deploying on my mac (High Sierra)

`MacBook-Pro:builder pyotr$ ./bldr download_file:master-server--prod,/root/.ssh/id_rsa.pub,/tmp,use_bootstrap_user=True
2018-08-17 01:56:51,573 botocore.credentials [INFO] Found credentials in shared credentials file: ~/.aws/credentials
INFO - botocore.credentials - Found credentials in shared credentials file: ~/.aws/credentials
2018-08-17 01:56:51,711 botocore.vendored.requests.packages.urllib3.connectionpool [INFO] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
INFO - botocore.vendored.requests.packages.urllib3.connectionpool - Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
Traceback (most recent call last):
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/venv/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/venv/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/venv/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/src/decorators.py", line 97, in call
    return func(stackname, *args, **kwargs)
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/src/cfn.py", line 299, in download_file
    _download(path, destination)
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/venv/lib/python2.7/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/src/cfn.py", line 294, in _download
    with stack_conn(stackname, username=BOOTSTRAP_USER if use_bootstrap_user else DEPLOY_USER, node=node):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/src/buildercore/core.py", line 264, in stack_conn
    ensure(len(data) == 1 or node, "stack is clustered with %s nodes and no specific node provided" % len(data))
  File "/Users/pyotr/Documents/NIKITA/JOURNAL/journal-cms-master/builder/src/buildercore/utils.py", line 21, in ensure
    raise exception_class(msg)
AssertionError: stack is clustered with 0 nodes and no specific node provided`

also tried /Users/pyotr etc instead of /root/.shh - the same

**Comment by giorgiosironi** [comment]
If you are looking to reuse eLife software, take a look at https://github.com/libero/community as this repository is not meant for external use anymore. Is that your use case?

**Comment by pyotr** [comment]
@giorgiosironi yes i got u - but can't understand - the article on eLife about Continuum created after article about Libero - it looks like Continuum more new techonology and open-use? Where is article about you stopped it for external use? In Libero repositories i can't find something close to Continuum or journal cms ... Please could u clear it for me. Thank u.

ps we just wanted to run our journal to use Continuum project software...
